#!/bin/bash
#PBS -l walltime=12:00:00
#PBS -l mem=40GB
#PBS -l ncpus=31
#PBS -l jobfs=30GB
#PBS -l storage=gdata/k10+gdata/hh5+scratch/k10+gdata/er8+scratch/er8+gdata/ra22+gdata/rq0

#PBS -l other=hyperthread
#PBS -q normal
#PBS -P er8

module use /g/data3/hh5/public/modules
module load conda/analysis3
conda

mpirun python3 /g/data/er8/lightning/chizhang/lightning_jump.py -l "Brisbane_,2021-12-,6,20,2,1" >& /g/data/er8/lightning/chizhang/output.log