#!/bin/bash
#PBS -l walltime=12:00:00
#PBS -l mem=40GB
#PBS -l ncpus=30
#PBS -l jobfs=30GB
#PBS -l storage=gdata/k10+gdata/hh5+scratch/k10+gdata/er8+scratch/er8+gdata/ra22+gdata/rq0

#PBS -l other=hyperthread
#PBS -q normal
#PBS -P er8

module use /g/data3/hh5/public/modules
module load conda/analysis3
conda

mpirun python3 /g/data/er8/lightning/chizhang/shi_collection.py -l "Brisbane_,2021-11-,202111,0.5,50,10,3" >& /g/data/er8/lightning/chizhang/output.log